development:
  adapter: postgresql
  database: expert_advice_project_dev
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: postgres
  password: password

test:
  adapter: postgresql
  database: expert_advise__project_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  min_messages: WARNING
  user: postgres
  password: password
